/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WebService;

import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;

/**
 *
 * @author Rohan
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jTextField1.setToolTipText("Username");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("UserName");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private String checkLoginID(String userID) {
        String typeOfCust = "";
        if (userID.length() == 8) {
            if (userID.substring(0, 3).equals("ATW") || userID.substring(0, 3).equals("OUT") || userID.substring(0, 3).equals("VER")) {
                if (userID.charAt(3) == 'A') {
                    typeOfCust = "A";
                } else if (userID.charAt(3) == 'C') {
                    typeOfCust = "C";
                } else {
                    typeOfCust = "X";
                }
            } else {
                typeOfCust = "X";
            }
        } else {
            typeOfCust = "X";
        }
        return typeOfCust;
    }

    private void LogWritterGeneral(String userID, String id, String value) {
        String date = new SimpleDateFormat("yyyyMMdd").format(new Date());
        String directory = "C:\\Users\\Rohan\\Documents\\NetBeansProjects\\WebService_Logs" + date;
        try {

            Path path = Paths.get(directory);

            Files.createDirectories(path);

        } catch (IOException e) {
            System.err.println("Failed to create directory!" + e.getMessage());
        }

        String fileName = "C:\\Users\\Rohan\\Documents\\NetBeansProjects\\WebService_Logs" + date + "\\" + userID + ".txt";
        try {
            String datecurr = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(new Date());
            FileWriter myWriter = new FileWriter(fileName, true);
            myWriter.write("\r\n---------------------" + datecurr + "-----------------------\r\n");
            myWriter.write("Request Type : " + id + "\r\n");
            myWriter.write("Value : " + value + "\r\n");
            myWriter.write("---------------------------------------------------------------\r\n");
            myWriter.close();

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      try{
        URL urlATW = new URL("http://192.168.56.1:8080/movieATW?wsdl");
        QName qNameATW = new QName("http://WebService/", "ATWImplService");
        Service serviceATW = Service.create(urlATW, qNameATW);
        IATW atw = serviceATW.getPort(IATW.class);

        URL urlVER = new URL("http://192.168.56.1:8081/movieVER?wsdl");
        QName qNameVER = new QName("http://WebService/", "VERImplService");
        Service serviceVER = Service.create(urlVER, qNameVER);
        IVER ver = serviceVER.getPort(IVER.class);

        URL urlOUT = new URL("http://192.168.56.1:8082/movieOUT?wsdl");
        QName qNameOUT = new QName("http://WebService/", "OUTImplService");
        Service serviceOUT = Service.create(urlOUT, qNameOUT);
        IOUT out = serviceOUT.getPort(IOUT.class);
        
        String userID = jTextField1.getText();
        String typeofcust = checkLoginID(userID);
        String userCheckServer = "";
        if (userID.substring(0, 3).equals("ATW")) {
            userCheckServer = atw.checkUserExists(userID);
        } else if (userID.substring(0, 3).equals("VER")) {
            userCheckServer = ver.checkUserExists(userID);
        } else if (userID.substring(0, 3).equals("OUT")) {
            userCheckServer = out.checkUserExists(userID);
        }
        if (!userCheckServer.equals("y")) {
            JOptionPane.showMessageDialog(this, "User ID does not exist!!");
        } else {

            switch (typeofcust) {
                case "A":
                    LogWritterGeneral(userID, "Login", "Admin");
                    try {
                        LogWritterGeneral(userID, "Admin " + userID, "LoggedIn");

                        Admin adminFrame = new Admin(userID);
                        adminFrame.setVisible(true);
                        this.dispose();

                    } catch (Exception e) {
                        LogWritterGeneral(userID, "Exception Occured", e.toString());

                        System.out.println(e);
                        JOptionPane.showMessageDialog(this, e);
                    }
//                                  

                    break;
                case "C":
                    LogWritterGeneral(userID, "Login", "Client");
                    try {
                        LogWritterGeneral(userID, "Customer " + userID, "LoggedIn");
                        JOptionPane.showMessageDialog(this, "Customer Logged In");
                        Customer custFrame = new Customer(userID);
                        custFrame.setVisible(true);
                        this.dispose();
                    } catch (Exception e) {
                        LogWritterGeneral(userID, "Exception Occured", e.toString());

                        System.err.println(e);
                    }
//                                    
                    break;
                default:
                    LogWritterGeneral(userID, "Login", "Invalid User ID");
                    JOptionPane.showMessageDialog(this, "Invalid Customer ID. Please Try Again");
                    break;
            }
        }
      }
      catch(Exception e){
          System.out.println(e);
           JOptionPane.showMessageDialog(this, e);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
